# Generated by Django 6.0.6 on 2026-09-19 14:05

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='Name')),
                ('subject_type', models.CharField(blank=True, max_length=64, verbose_name='Subject type')),
                ('subject_id', models.CharField(blank=True, max_length=64, verbose_name='Subject id')),
                ('props', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Properties')),
                ('source', models.CharField(choices=[('server', 'Server'), ('client', 'Client')], default='server', max_length=8, verbose_name='Source')),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created')),
                ('actor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['name', 'created'], name='analytics_event_name_created')],
            },
        ),
    ]
