# Generated by Django 6.0.1 on 2026-06-27 03:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AthleteProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "training_started",
                    models.DateField(
                        blank=True, null=True, verbose_name="Training started"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Time last modified"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="athlete_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Athlete profile",
                "verbose_name_plural": "Athlete profiles",
            },
        ),
        migrations.CreateModel(
            name="CoachProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Display name"
                    ),
                ),
                (
                    "programming_style",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of short style tags, e.g. ['Compound-first', 'RPE-based load'].",
                        verbose_name="Programming style",
                    ),
                ),
                (
                    "avoid_rules",
                    models.TextField(blank=True, verbose_name="Avoid rules"),
                ),
                (
                    "default_unit",
                    models.CharField(
                        choices=[("kg", "Kilograms"), ("lb", "Pounds")],
                        default="kg",
                        max_length=2,
                        verbose_name="Default unit",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Time last modified"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coach_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coach profile",
                "verbose_name_plural": "Coach profiles",
            },
        ),
        migrations.CreateModel(
            name="Contraindication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=255, verbose_name="Contraindication"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contraindications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Athlete",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contraindication",
                "verbose_name_plural": "Contraindications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CoachAthlete",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_coach_invite", "Pending athlete acceptance"),
                            ("pending_athlete_request", "Pending coach acceptance"),
                            ("active", "Active"),
                            ("declined", "Declined"),
                            ("ended", "Ended"),
                        ],
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                (
                    "invited_by",
                    models.CharField(
                        choices=[("coach", "Coach"), ("athlete", "Athlete")],
                        max_length=8,
                        verbose_name="Invited by",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Time responded"
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Time ended"
                    ),
                ),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coach_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Athlete",
                    ),
                ),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="athlete_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Coach",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coach-athlete link",
                "verbose_name_plural": "Coach-athlete links",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("coach", "athlete"), name="unique_coach_athlete"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("coach", models.F("athlete")), _negated=True
                        ),
                        name="coach_athlete_distinct",
                    ),
                ],
            },
        ),
    ]
