# Generated by Django 6.0.1 on 2026-06-27 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0002_auto_20201204_2000"),
        ("meso", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.PositiveIntegerField(verbose_name="Day number")),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, verbose_name="Name"),
                ),
                (
                    "bias",
                    models.CharField(blank=True, max_length=255, verbose_name="Bias"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Session",
                "verbose_name_plural": "Sessions",
                "ordering": ["order", "day_number"],
            },
        ),
        migrations.CreateModel(
            name="ExercisePrescription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "sets",
                    models.CharField(blank=True, max_length=32, verbose_name="Sets"),
                ),
                (
                    "reps",
                    models.CharField(blank=True, max_length=32, verbose_name="Reps"),
                ),
                (
                    "load",
                    models.CharField(blank=True, max_length=32, verbose_name="Load"),
                ),
                (
                    "rpe",
                    models.CharField(blank=True, max_length=32, verbose_name="RPE"),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="Note"),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="Tags"),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meso_prescriptions",
                        to="exercises.exercise",
                        verbose_name="Catalog exercise",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="meso.session",
                        verbose_name="Session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exercise prescription",
                "verbose_name_plural": "Exercise prescriptions",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "goal",
                    models.CharField(blank=True, max_length=255, verbose_name="Goal"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("kg", "Kilograms"), ("lb", "Pounds")],
                        default="kg",
                        max_length=2,
                        verbose_name="Unit",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Time last modified"
                    ),
                ),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="meso.coachathlete",
                        verbose_name="Relationship",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan",
                "verbose_name_plural": "Plans",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Mesocycle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "week_count",
                    models.PositiveIntegerField(default=4, verbose_name="Week count"),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mesocycles",
                        to="meso.plan",
                        verbose_name="Plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mesocycle",
                "verbose_name_plural": "Mesocycles",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SessionLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="Date")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("done", "Done")],
                        default="pending",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meso_session_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Athlete",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="meso.session",
                        verbose_name="Session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session log",
                "verbose_name_plural": "Session logs",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoggedSet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "set_number",
                    models.PositiveIntegerField(default=1, verbose_name="Set number"),
                ),
                (
                    "reps",
                    models.CharField(blank=True, max_length=32, verbose_name="Reps"),
                ),
                (
                    "load",
                    models.CharField(blank=True, max_length=32, verbose_name="Load"),
                ),
                (
                    "rpe",
                    models.CharField(blank=True, max_length=32, verbose_name="RPE"),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logged_sets",
                        to="meso.exerciseprescription",
                        verbose_name="Prescription",
                    ),
                ),
                (
                    "session_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="meso.sessionlog",
                        verbose_name="Session log",
                    ),
                ),
            ],
            options={
                "verbose_name": "Logged set",
                "verbose_name_plural": "Logged sets",
                "ordering": ["set_number"],
            },
        ),
        migrations.CreateModel(
            name="Week",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveIntegerField(verbose_name="Week number")),
                (
                    "phase",
                    models.CharField(blank=True, max_length=64, verbose_name="Phase"),
                ),
                (
                    "volume",
                    models.PositiveIntegerField(default=0, verbose_name="Volume"),
                ),
                (
                    "intensity",
                    models.PositiveIntegerField(default=0, verbose_name="Intensity"),
                ),
                (
                    "is_deload",
                    models.BooleanField(default=False, verbose_name="Deload"),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="Current"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Delivered at"
                    ),
                ),
                (
                    "mesocycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weeks",
                        to="meso.mesocycle",
                        verbose_name="Mesocycle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Week",
                "verbose_name_plural": "Weeks",
                "ordering": ["index"],
            },
        ),
        migrations.AddField(
            model_name="session",
            name="week",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="meso.week",
                verbose_name="Week",
            ),
        ),
        migrations.AddConstraint(
            model_name="mesocycle",
            constraint=models.UniqueConstraint(
                fields=("plan", "order"), name="unique_mesocycle_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="week",
            constraint=models.UniqueConstraint(
                fields=("mesocycle", "index"), name="unique_week_index"
            ),
        ),
    ]
