# Generated by Django 6.0.1 on 2026-06-27 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meso", "0002_session_exerciseprescription_plan_mesocycle_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeekDelivery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivered_at", models.DateTimeField(verbose_name="Delivered at")),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="Payload"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="meso.week",
                        verbose_name="Week",
                    ),
                ),
            ],
            options={
                "verbose_name": "Week delivery",
                "verbose_name_plural": "Week deliveries",
                "ordering": ["-delivered_at"],
            },
        ),
    ]
