# Generated by Django 6.0.1 on 2026-06-27 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meso", "0003_weekdelivery"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentProposalBatch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instruction", models.TextField(verbose_name="Instruction")),
                ("summary", models.TextField(blank=True, verbose_name="Agent summary")),
                (
                    "model",
                    models.CharField(blank=True, max_length=64, verbose_name="Model"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("applied", "Applied"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meso_proposal_batches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Coach",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposal_batches",
                        to="meso.plan",
                        verbose_name="Plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent proposal batch",
                "verbose_name_plural": "Agent proposal batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProposedChange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("swap", "Swap"),
                            ("progress", "Progress"),
                            ("volume", "Volume"),
                            ("deload", "Deload"),
                        ],
                        max_length=16,
                        verbose_name="Kind",
                    ),
                ),
                (
                    "day_label",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Day label"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "before",
                    models.CharField(blank=True, max_length=255, verbose_name="Before"),
                ),
                (
                    "after",
                    models.CharField(blank=True, max_length=255, verbose_name="After"),
                ),
                ("rationale", models.TextField(blank=True, verbose_name="Rationale")),
                (
                    "honors",
                    models.CharField(blank=True, max_length=255, verbose_name="Honors"),
                ),
                (
                    "introduces_exercise",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Introduces exercise"
                    ),
                ),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="Payload"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="meso.agentproposalbatch",
                        verbose_name="Batch",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposed_changes",
                        to="meso.exerciseprescription",
                        verbose_name="Prescription",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposed_changes",
                        to="meso.session",
                        verbose_name="Session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposed change",
                "verbose_name_plural": "Proposed changes",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
