# Generated by Django 6.0.1 on 2026-06-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meso", "0004_agentproposalbatch_proposedchange"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentproposalbatch",
            name="error",
            field=models.TextField(blank=True, verbose_name="Error"),
        ),
        migrations.AlterField(
            model_name="agentproposalbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("drafting", "Drafting"),
                    ("pending", "Pending review"),
                    ("failed", "Failed"),
                    ("applied", "Applied"),
                    ("dismissed", "Dismissed"),
                ],
                default="pending",
                max_length=16,
                verbose_name="Status",
            ),
        ),
    ]
