# Generated by Django 6.0.1 on 2026-06-28 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meso", "0005_agentproposalbatch_error_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        max_length=512, unique=True, verbose_name="Endpoint"
                    ),
                ),
                ("p256dh", models.CharField(max_length=255, verbose_name="P256DH key")),
                ("auth", models.CharField(max_length=255, verbose_name="Auth secret")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meso_push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Athlete",
                    ),
                ),
            ],
            options={
                "verbose_name": "Push subscription",
                "verbose_name_plural": "Push subscriptions",
                "ordering": ["-created_at"],
            },
        ),
    ]
