# Generated by Django 6.0.1 on 2026-06-28 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meso", "0007_mesogroup_groupmembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plans",
                to="meso.mesogroup",
                verbose_name="Group",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="relationship",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plans",
                to="meso.coachathlete",
                verbose_name="Relationship",
            ),
        ),
        migrations.AddConstraint(
            model_name="plan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("group__isnull", True), ("relationship__isnull", False)),
                    models.Q(("group__isnull", False), ("relationship__isnull", True)),
                    _connector="OR",
                ),
                name="plan_relationship_xor_group",
            ),
        ),
    ]
