# Generated by Django 6.0.1 on 2026-06-28 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meso", "0008_plan_group_root"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrescriptionOverride",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "swap_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Swap exercise"
                    ),
                ),
                (
                    "load_pct",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Load %"
                    ),
                ),
                (
                    "sets",
                    models.CharField(blank=True, max_length=32, verbose_name="Sets"),
                ),
                (
                    "reps",
                    models.CharField(blank=True, max_length=32, verbose_name="Reps"),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="Note"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Time last modified"
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides",
                        to="meso.groupmembership",
                        verbose_name="Membership",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides",
                        to="meso.exerciseprescription",
                        verbose_name="Prescription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescription override",
                "verbose_name_plural": "Prescription overrides",
                "ordering": ["prescription_id", "membership_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("membership", "prescription"),
                        name="unique_prescription_override",
                    )
                ],
            },
        ),
    ]
