# Generated by Django 6.0.1 on 2026-06-28 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meso", "0009_prescriptionoverride"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="source_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materialized_plans",
                to="meso.mesogroup",
                verbose_name="Source group",
            ),
        ),
        migrations.AddConstraint(
            model_name="plan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_group__isnull", False)),
                fields=("relationship", "source_group"),
                name="unique_materialized_group_plan",
            ),
        ),
    ]
