# Generated by Django 6.0.1 on 2026-06-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meso", "0010_plan_source_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="exerciseprescription",
            name="load_type",
            field=models.CharField(
                choices=[("abs", "Absolute load"), ("pct", "% of 1RM")],
                default="abs",
                max_length=3,
                verbose_name="Load type",
            ),
        ),
    ]
