# Generated by Django 6.0.1 on 2026-06-29 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0002_auto_20201204_2000"),
        ("meso", "0011_exerciseprescription_load_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AthleteOneRm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Lift name")),
                (
                    "key",
                    models.CharField(
                        editable=False, max_length=300, verbose_name="Lift key"
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="Estimated 1RM"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("kg", "Kilograms"), ("lb", "Pounds")],
                        default="kg",
                        max_length=2,
                        verbose_name="Unit",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Time last modified"
                    ),
                ),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meso_one_rms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Athlete",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meso_one_rms",
                        to="exercises.exercise",
                        verbose_name="Catalog exercise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Athlete 1RM",
                "verbose_name_plural": "Athlete 1RMs",
                "ordering": ["athlete_id", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("athlete", "key"), name="unique_athlete_one_rm"
                    )
                ],
            },
        ),
    ]
