# Generated by Django 6.0.1 on 2026-06-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meso", "0013_backfill_one_rms"),
    ]

    operations = [
        migrations.AddField(
            model_name="athleteonerm",
            name="source",
            field=models.CharField(
                choices=[
                    ("logged", "Auto-derived from logs"),
                    ("manual", "Athlete-entered"),
                ],
                default="logged",
                max_length=10,
                verbose_name="Source",
            ),
        ),
    ]
