# Generated by Django 6.0.1 on 2026-06-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meso", "0015_coachinvite"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachinvite",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the claim link stops working. Null = never expires (legacy invites predating the TTL).",
                null=True,
                verbose_name="Expires at",
            ),
        ),
        migrations.AlterField(
            model_name="coachinvite",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("revoked", "Revoked"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=16,
                verbose_name="Status",
            ),
        ),
    ]
