# Generated by Django 6.0.1 on 2026-06-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meso", "0016_coachinvite_expiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachinvite",
            name="reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the expiry-reminder email went out. Null = not yet reminded this arming cycle; cleared on resend.",
                null=True,
                verbose_name="Reminder sent at",
            ),
        ),
    ]
