# Generated by Django 6.0.1 on 2026-06-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meso", "0018_register_invite_schedules"),
    ]

    operations = [
        migrations.AddField(
            model_name="athleteprofile",
            name="delivery_email_opt_out",
            field=models.BooleanField(
                default=False,
                help_text="Set when the athlete unsubscribes from training-delivery emails (the email's List-Unsubscribe link). Web push is unaffected.",
                verbose_name="Opted out of delivery emails",
            ),
        ),
    ]
