# Generated by Django 6.0.1 on 2026-06-29 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meso", "0019_athleteprofile_delivery_email_opt_out"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoachSubscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("trialing", "Trialing"),
                            ("active", "Active"),
                            ("past_due", "Past due"),
                            ("canceled", "Canceled"),
                            ("comped", "Comped"),
                        ],
                        default="free",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Null until the coach actually subscribes (enters a card).",
                        max_length=255,
                        verbose_name="Stripe subscription id",
                    ),
                ),
                (
                    "stripe_item_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The subscription line item — for seat-quantity updates.",
                        max_length=255,
                        verbose_name="Stripe subscription item id",
                    ),
                ),
                (
                    "trial_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set locally when the no-card trial starts; null = never trialed.",
                        null=True,
                        verbose_name="Trial ends at",
                    ),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="Mirrored from Stripe for paid coaches.",
                        null=True,
                        verbose_name="Current period ends at",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Last seat count synced to Stripe — a cache, not the truth.",
                        verbose_name="Synced seat quantity",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Time last modified"
                    ),
                ),
                (
                    "coach",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coach_subscription",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Coach",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coach subscription",
                "verbose_name_plural": "Coach subscriptions",
            },
        ),
    ]
