# Generated by Django 6.0.1 on 2026-06-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meso", "0021_register_reconcile_seats_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachathlete",
            name="is_demo",
            field=models.BooleanField(default=False, verbose_name="Demo relationship"),
        ),
        migrations.AddField(
            model_name="mesogroup",
            name="is_demo",
            field=models.BooleanField(default=False, verbose_name="Demo group"),
        ),
    ]
