# Generated by Django 6.0.1 on 2026-06-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meso", "0022_coachathlete_is_demo_mesogroup_is_demo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposedchange",
            name="kind",
            field=models.CharField(
                choices=[
                    ("swap", "Swap"),
                    ("progress", "Progress"),
                    ("volume", "Volume"),
                    ("deload", "Deload"),
                    ("add", "Add"),
                ],
                max_length=16,
                verbose_name="Kind",
            ),
        ),
    ]
