# Generated by Django 6.0.1 on 2026-06-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meso", "0023_alter_proposedchange_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachsubscription",
            name="stripe_base_item_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The flat base ($9.99/mo) line item, fixed at quantity 1 (S6 Phase 6). Seat sync only resizes the per-seat item, never this one.",
                max_length=255,
                verbose_name="Stripe base subscription item id",
            ),
        ),
        migrations.AlterField(
            model_name="coachsubscription",
            name="stripe_item_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The per-seat subscription line item — for seat-quantity updates.",
                max_length=255,
                verbose_name="Stripe subscription item id",
            ),
        ),
    ]
