# Generated by Django 6.0.1 on 2026-06-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meso", "0024_coachsubscription_stripe_base_item_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentproposalbatch",
            name="api_calls",
            field=models.PositiveIntegerField(default=1, verbose_name="API calls"),
        ),
        migrations.AddField(
            model_name="agentproposalbatch",
            name="billing_status",
            field=models.CharField(
                blank=True, max_length=16, verbose_name="Billing status at run time"
            ),
        ),
        migrations.AddField(
            model_name="agentproposalbatch",
            name="cache_creation_input_tokens",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Cache-write input tokens"
            ),
        ),
        migrations.AddField(
            model_name="agentproposalbatch",
            name="cache_read_input_tokens",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Cache-read input tokens"
            ),
        ),
        migrations.AddField(
            model_name="agentproposalbatch",
            name="duration_ms",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Duration (ms)"
            ),
        ),
        migrations.AddField(
            model_name="agentproposalbatch",
            name="estimated_cost_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=10,
                null=True,
                verbose_name="Estimated cost (USD)",
            ),
        ),
        migrations.AddField(
            model_name="agentproposalbatch",
            name="input_tokens",
            field=models.PositiveIntegerField(default=0, verbose_name="Input tokens"),
        ),
        migrations.AddField(
            model_name="agentproposalbatch",
            name="output_tokens",
            field=models.PositiveIntegerField(default=0, verbose_name="Output tokens"),
        ),
        migrations.AddField(
            model_name="agentproposalbatch",
            name="request_id",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Anthropic request id"
            ),
        ),
        migrations.AddField(
            model_name="agentproposalbatch",
            name="stop_reason",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="Stop reason"
            ),
        ),
        migrations.AddField(
            model_name="agentproposalbatch",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("draft", "Draft with AI"),
                    ("eval", "Eval"),
                    ("group", "Group"),
                ],
                default="manual",
                max_length=16,
                verbose_name="Trigger",
            ),
        ),
    ]
