# Generated by Django 6.0.1 on 2026-06-30 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meso", "0026_register_margin_alert_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposedchange",
            name="membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proposed_changes",
                to="meso.groupmembership",
                verbose_name="Membership",
            ),
        ),
        migrations.AlterField(
            model_name="proposedchange",
            name="kind",
            field=models.CharField(
                choices=[
                    ("swap", "Swap"),
                    ("progress", "Progress"),
                    ("volume", "Volume"),
                    ("deload", "Deload"),
                    ("add", "Add"),
                    ("adjust", "Adjust"),
                ],
                max_length=16,
                verbose_name="Kind",
            ),
        ),
    ]
