# Generated by Django 6.0.6 on 2026-07-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meso', '0030_register_sandbox_expiry_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseprescription',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deleted at'),
        ),
        migrations.AddField(
            model_name='session',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deleted at'),
        ),
        migrations.AddField(
            model_name='week',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deleted at'),
        ),
    ]
