# Generated by Django 6.0.6 on 2026-07-02 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meso', '0031_exerciseprescription_deleted_at_session_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack', models.CharField(choices=[('undo', 'Undo'), ('redo', 'Redo')], default='undo', max_length=8, verbose_name='Stack')),
                ('seq', models.PositiveIntegerField(verbose_name='Sequence')),
                ('label', models.CharField(max_length=80, verbose_name='Label')),
                ('snapshot', models.JSONField(verbose_name='Snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='meso.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Plan action',
                'verbose_name_plural': 'Plan actions',
                'ordering': ['seq'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'stack', 'seq'), name='unique_plan_action_seq')],
            },
        ),
    ]
