# Generated by Django 6.0.6 on 2026-07-07 20:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meso', '0032_planaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coachathlete',
            name='coach_athlete_distinct',
        ),
        migrations.AddField(
            model_name='coachathlete',
            name='is_self',
            field=models.BooleanField(default=False, verbose_name='Self-coaching relationship'),
        ),
        migrations.AddConstraint(
            model_name='coachathlete',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('coach', models.F('athlete')), ('is_self', True)), models.Q(models.Q(('coach', models.F('athlete')), _negated=True), ('is_self', False)), _connector='OR'), name='coach_athlete_distinct_unless_self'),
        ),
    ]
