# Generated by Django 6.0.6 on 2026-07-07 21:56

import django.db.models.deletion
from django.db import migrations, models


def clear_reshaped_program_data(apps, schema_editor):
    """Pre-launch reshape (no data to preserve): clear the program/logging/agent/
    override rows the fixed-lineup cutover reshapes so the schema ops below apply
    cleanly to a *populated* dev/prod DB — the new NOT NULL ``Session.session_slot``
    FK and the repointed ``prescription`` FKs would otherwise violate their
    constraints against pre-existing rows. On a fresh test DB these tables are
    already empty, so this is a no-op there. The demo is rebuilt post-deploy by
    ``seed_meso_demo`` (idempotent). Plan/Mesocycle/Week rows are left intact — the
    reseeder repopulates their slots/cells. Irreversible (reverse = no-op).
    """
    for label in (
        "LoggedSet",
        "SessionLog",
        "PrescriptionOverride",
        "ProposedChange",
        "ExercisePrescription",
        "Session",
    ):
        apps.get_model("meso", label).objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20201204_2000'),
        ('meso', '0032_planaction'),
    ]

    operations = [
        migrations.RunPython(
            clear_reshaped_program_data, migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='exerciseprescription',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='exerciseprescription',
            name='session',
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['session_slot__order', 'session_slot__day_number'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.RemoveField(
            model_name='session',
            name='bias',
        ),
        migrations.RemoveField(
            model_name='session',
            name='day_number',
        ),
        migrations.RemoveField(
            model_name='session',
            name='name',
        ),
        migrations.RemoveField(
            model_name='session',
            name='order',
        ),
        migrations.CreateModel(
            name='ExerciseSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deleted at')),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meso_exercise_slots', to='exercises.exercise', verbose_name='Catalog exercise')),
            ],
            options={
                'verbose_name': 'Exercise slot',
                'verbose_name_plural': 'Exercise slots',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.CharField(blank=True, max_length=32, verbose_name='Sets')),
                ('reps', models.CharField(blank=True, max_length=32, verbose_name='Reps')),
                ('load', models.CharField(blank=True, max_length=32, verbose_name='Load')),
                ('load_type', models.CharField(choices=[('abs', 'Absolute load'), ('pct', '% of 1RM')], default='abs', max_length=3, verbose_name='Load type')),
                ('rpe', models.CharField(blank=True, max_length=32, verbose_name='RPE')),
                ('rest', models.CharField(blank=True, max_length=32, verbose_name='Rest')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('skipped', models.BooleanField(default=False, verbose_name='Skipped')),
                ('swap_name', models.CharField(blank=True, max_length=255, verbose_name='Swap name')),
                ('exercise_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='meso.exerciseslot', verbose_name='Exercise slot')),
                ('swap_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meso_cell_swaps', to='exercises.exercise', verbose_name='Swap exercise')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='meso.week', verbose_name='Week')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['exercise_slot__order'],
            },
        ),
        migrations.AlterField(
            model_name='loggedset',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_sets', to='meso.prescription', verbose_name='Prescription'),
        ),
        migrations.AlterField(
            model_name='prescriptionoverride',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='meso.prescription', verbose_name='Prescription'),
        ),
        migrations.AlterField(
            model_name='proposedchange',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_changes', to='meso.prescription', verbose_name='Prescription'),
        ),
        migrations.CreateModel(
            name='SessionSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(verbose_name='Day number')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('bias', models.CharField(blank=True, max_length=255, verbose_name='Bias')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deleted at')),
                ('mesocycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_slots', to='meso.mesocycle', verbose_name='Mesocycle')),
            ],
            options={
                'verbose_name': 'Session slot',
                'verbose_name_plural': 'Session slots',
                'ordering': ['order', 'day_number'],
            },
        ),
        migrations.AddField(
            model_name='exerciseslot',
            name='session_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_slots', to='meso.sessionslot', verbose_name='Session slot'),
        ),
        migrations.AddField(
            model_name='session',
            name='session_slot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='meso.sessionslot', verbose_name='Session slot'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('week', 'session_slot'), name='unique_session_week_slot'),
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.UniqueConstraint(fields=('exercise_slot', 'week'), name='unique_cell_slot_week'),
        ),
        migrations.DeleteModel(
            name='ExercisePrescription',
        ),
    ]
