# Generated by Django 6.0.6 on 2026-07-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meso", "0033_remove_coachathlete_coach_athlete_distinct_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachprofile",
            name="tour_state",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Guided demo onboarding tour progress (issue #430): {'step': <int>, 'status': 'active'|'dismissed'|'completed'}. An empty dict means the tour has never started.",
                verbose_name="Guided tour state",
            ),
        ),
    ]
