# Generated by Django 6.0.6 on 2026-07-07 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("meso", "0034_coachprofile_tour_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TourEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("advanced", "Step advanced"),
                            ("opt_in", "Segment/self-action opt-in"),
                            ("dismissed", "Dismissed"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped (load everything)"),
                        ],
                        max_length=16,
                        verbose_name="Kind",
                    ),
                ),
                (
                    "variant",
                    models.CharField(
                        choices=[
                            ("sandbox", "Sandbox"),
                            ("self", "Real coach (self-coaching)"),
                        ],
                        max_length=8,
                        verbose_name="Variant",
                    ),
                ),
                (
                    "step_key",
                    models.CharField(
                        blank=True,
                        help_text="The tour.STEPS key this event happened at/for, e.g. 'designer'.",
                        max_length=32,
                        verbose_name="Step key",
                    ),
                ),
                (
                    "segment",
                    models.CharField(
                        blank=True,
                        help_text="For opt_in events only: the demo segment (athletes/program/delivery/log/group) or self-variant action (roster_add_self/plan_create) that was opted into.",
                        max_length=32,
                        verbose_name="Segment / action",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "coach",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tour_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Coach",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tour event",
                "verbose_name_plural": "Tour events",
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["kind", "created"], name="meso_tourev_kind_ebe7db_idx"
                    ),
                    models.Index(
                        fields=["coach", "created"],
                        name="meso_tourev_coach_i_21040d_idx",
                    ),
                ],
            },
        ),
    ]
