# Generated by Django 6.0.6 on 2026-07-07 21:56

import django.db.models.deletion
from django.db import migrations, models


def reset_program_data(apps, schema_editor):
    """Pre-launch reshape (no data to preserve): delete every ``Plan`` so the
    fixed-lineup schema ops below apply to empty program tables AND the demo
    rebuilds cleanly post-deploy.

    Deleting the plans cascades the WHOLE program hierarchy — mesocycles → weeks →
    sessions → prescriptions/logs/deliveries, agent batches → proposed changes, and
    the designer undo/redo ``PlanAction`` stacks — while leaving the coach/athlete/
    group/subscription scaffolding intact (``Plan`` FKs *to* those; they are not
    cascaded). This matters because:

    - the new NOT NULL ``Session.session_slot`` FK and the repointed ``prescription``
      FKs would otherwise violate their constraints against pre-existing rows;
    - ``seed_meso_demo`` early-returns when ``plan.mesocycles.exists()`` and the group
      path only builds when the shared plan is missing, so leaving empty
      ``Mesocycle``/``Week`` shells behind would leave delivered-but-empty programs the
      reseeder never rebuilds — deleting the plans resets to the fresh-DB state the
      reseeder is built to populate (idempotent), which recreates the new-shape tree;
    - stale ``PlanAction`` snapshots reference the retired per-week rows, so an undo
      after the cutover would restore an old-shape snapshot with no slots/cells — the
      cascade drops those stacks with their plans.

    On a fresh test DB there are no plans, so this is a no-op there. Reseed with
    ``manage.py seed_meso_demo`` after the deploy. Irreversible (reverse = no-op).
    """
    apps.get_model("meso", "Plan").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20201204_2000'),
        ('meso', '0035_tourevent'),
    ]

    operations = [
        migrations.RunPython(reset_program_data, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='exerciseprescription',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='exerciseprescription',
            name='session',
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['session_slot__order', 'session_slot__day_number'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.RemoveField(
            model_name='session',
            name='bias',
        ),
        migrations.RemoveField(
            model_name='session',
            name='day_number',
        ),
        migrations.RemoveField(
            model_name='session',
            name='name',
        ),
        migrations.RemoveField(
            model_name='session',
            name='order',
        ),
        migrations.CreateModel(
            name='ExerciseSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deleted at')),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meso_exercise_slots', to='exercises.exercise', verbose_name='Catalog exercise')),
            ],
            options={
                'verbose_name': 'Exercise slot',
                'verbose_name_plural': 'Exercise slots',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.CharField(blank=True, max_length=32, verbose_name='Sets')),
                ('reps', models.CharField(blank=True, max_length=32, verbose_name='Reps')),
                ('load', models.CharField(blank=True, max_length=32, verbose_name='Load')),
                ('load_type', models.CharField(choices=[('abs', 'Absolute load'), ('pct', '% of 1RM')], default='abs', max_length=3, verbose_name='Load type')),
                ('rpe', models.CharField(blank=True, max_length=32, verbose_name='RPE')),
                ('rest', models.CharField(blank=True, max_length=32, verbose_name='Rest')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('skipped', models.BooleanField(default=False, verbose_name='Skipped')),
                ('swap_name', models.CharField(blank=True, max_length=255, verbose_name='Swap name')),
                ('exercise_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='meso.exerciseslot', verbose_name='Exercise slot')),
                ('swap_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meso_cell_swaps', to='exercises.exercise', verbose_name='Swap exercise')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='meso.week', verbose_name='Week')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['exercise_slot__order'],
            },
        ),
        migrations.AlterField(
            model_name='loggedset',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_sets', to='meso.prescription', verbose_name='Prescription'),
        ),
        migrations.AlterField(
            model_name='prescriptionoverride',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='meso.prescription', verbose_name='Prescription'),
        ),
        migrations.AlterField(
            model_name='proposedchange',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_changes', to='meso.prescription', verbose_name='Prescription'),
        ),
        migrations.CreateModel(
            name='SessionSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(verbose_name='Day number')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('bias', models.CharField(blank=True, max_length=255, verbose_name='Bias')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deleted at')),
                ('mesocycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_slots', to='meso.mesocycle', verbose_name='Mesocycle')),
            ],
            options={
                'verbose_name': 'Session slot',
                'verbose_name_plural': 'Session slots',
                'ordering': ['order', 'day_number'],
            },
        ),
        migrations.AddField(
            model_name='exerciseslot',
            name='session_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_slots', to='meso.sessionslot', verbose_name='Session slot'),
        ),
        migrations.AddField(
            model_name='session',
            name='session_slot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='meso.sessionslot', verbose_name='Session slot'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('week', 'session_slot'), name='unique_session_week_slot'),
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.UniqueConstraint(fields=('exercise_slot', 'week'), name='unique_cell_slot_week'),
        ),
        migrations.DeleteModel(
            name='ExercisePrescription',
        ),
    ]
