# Generated by Django 6.0.6 on 2026-07-16 19:58
#
# Phase 2a of the spreadsheet-parity plan (docs/meso/spreadsheet-parity-plan.md
# §2): a Prescription cell stops being seven structured fields and becomes one
# freeform ``text`` string per ``(exercise_slot, week, line)``. The RunPython
# step between the adds and the removes composes each existing cell's text
# from its old columns ("4 x 6, RPE 9, 225"-style — Lance's own notation),
# collapses the one-week ``swap_*``/``note`` exceptions into freeform
# sub-lines (line 1+, per §2.6), hoists the per-week ``rest`` up to the
# per-exercise ``ExerciseSlot.rest`` column (D2; a divergent week keeps its
# value inline in that cell's text), converts stored ``WeekDelivery`` payloads
# to the new exercise-dict shape so delivery diffs stay coherent, and WIPES the
# undo/redo stacks (``PlanAction``) — their snapshots capture the retired
# columns and cannot be replayed against the new schema. Fresh history accrues
# from the first post-deploy edit.

from collections import Counter
from collections import defaultdict

from django.db import migrations, models


def _compose_text(sets, reps, rpe, load, load_is_pct):
    """Frozen copy of ``parsing.compose_prescription_text`` (historical safety).

    Inlined so later changes to the live helper can never alter what this
    migration did. The seed data's em-dash RPE placeholder ("—") means "none".
    """
    sets = (sets or "").strip()
    reps = (reps or "").strip()
    rpe = (rpe or "").strip()
    load = (load or "").strip()
    if rpe in ("—", "-"):
        rpe = ""
    parts = []
    if sets and reps:
        parts.append(f"{sets} x {reps}")
    elif sets:
        parts.append(f"{sets} x ?")
    elif reps:
        parts.append(f"? x {reps}")
    if rpe:
        parts.append(rpe if rpe.lower().startswith("rpe") else f"RPE {rpe}")
    if load:
        if load_is_pct and not load.endswith("%"):
            load = f"{load}%"
        parts.append(load)
    return ", ".join(parts)


def _convert_payload_exercise(ex):
    """One WeekDelivery payload exercise dict, old shape → text-first shape."""
    if "text" in ex or "sets" not in ex:
        return ex, False
    lines = []
    swap = (ex.get("swap_name") or "").strip()
    if swap:
        lines.append(swap)
    note = (ex.get("note") or "").strip()
    if note:
        lines.append(note)
    converted = {
        "id": ex.get("id"),
        "name": ex.get("name"),
        "text": _compose_text(
            ex.get("sets"),
            ex.get("reps"),
            ex.get("rpe"),
            ex.get("load"),
            ex.get("load_type") == "pct",
        ),
        "skipped": ex.get("skipped", False),
        "tempo": "",
        "rest": ex.get("rest") or "",
        "note": "",
        "lines": [
            {"line": i, "text": text} for i, text in enumerate(lines, start=1)
        ],
    }
    if "tag" in ex:
        converted["tag"] = ex["tag"]
    return converted, True


def forwards(apps, schema_editor):
    Prescription = apps.get_model("meso", "Prescription")
    ExerciseSlot = apps.get_model("meso", "ExerciseSlot")
    Exercise = apps.get_model("exercises", "Exercise")
    PlanAction = apps.get_model("meso", "PlanAction")
    WeekDelivery = apps.get_model("meso", "WeekDelivery")

    cells = list(Prescription.objects.all().order_by("pk"))

    # Hoist rest to the slot (D2): the modal non-empty per-week value wins,
    # ties broken by first appearance; a cell whose rest differs keeps its
    # value inline in that week's text below.
    rest_by_slot = defaultdict(list)
    for cell in cells:
        if cell.rest:
            rest_by_slot[cell.exercise_slot_id].append(cell.rest)
    hoisted = {
        slot_id: Counter(values).most_common(1)[0][0]
        for slot_id, values in rest_by_slot.items()
    }
    for slot_id, rest in hoisted.items():
        ExerciseSlot.objects.filter(pk=slot_id).update(rest=rest)

    swap_exercise_ids = {c.swap_exercise_id for c in cells if c.swap_exercise_id}
    swap_names = dict(
        Exercise.objects.filter(pk__in=swap_exercise_ids).values_list("pk", "name")
    )

    sub_lines = []
    for cell in cells:
        text = _compose_text(
            cell.sets, cell.reps, cell.rpe, cell.load, cell.load_type == "pct"
        )
        slot_rest = hoisted.get(cell.exercise_slot_id, "")
        if cell.rest and cell.rest != slot_rest:
            text = f"{text}, rest {cell.rest}" if text else f"rest {cell.rest}"
        cell.text = text
        lines = []
        swap = cell.swap_name or swap_names.get(cell.swap_exercise_id, "")
        if swap:
            lines.append(swap)
        if cell.note:
            lines.append(cell.note)
        for line, line_text in enumerate(lines, start=1):
            sub_lines.append(
                Prescription(
                    exercise_slot_id=cell.exercise_slot_id,
                    week_id=cell.week_id,
                    line=line,
                    text=line_text,
                )
            )
    Prescription.objects.bulk_update(cells, ["text"], batch_size=500)
    if sub_lines:
        Prescription.objects.bulk_create(sub_lines, batch_size=500)

    # Undo/redo snapshots capture the retired columns — unreplayable now.
    PlanAction.objects.all().delete()

    for delivery in WeekDelivery.objects.all():
        payload = delivery.payload or {}
        changed = False
        for session in payload.get("sessions", []):
            exercises = session.get("exercises", [])
            for i, ex in enumerate(exercises):
                converted, did = _convert_payload_exercise(ex)
                if did:
                    exercises[i] = converted
                    changed = True
        if changed:
            delivery.payload = payload
            delivery.save(update_fields=["payload"])


class Migration(migrations.Migration):

    dependencies = [
        ("meso", "0037_fixed_lineup_schema_cutover"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prescription",
            options={
                "ordering": ["exercise_slot__order", "line"],
                "verbose_name": "Prescription",
                "verbose_name_plural": "Prescriptions",
            },
        ),
        migrations.RemoveConstraint(
            model_name="prescription",
            name="unique_cell_slot_week",
        ),
        migrations.AddField(
            model_name="exerciseslot",
            name="note",
            field=models.TextField(blank=True, verbose_name="Instructions"),
        ),
        migrations.AddField(
            model_name="exerciseslot",
            name="rest",
            field=models.CharField(blank=True, max_length=64, verbose_name="Rest"),
        ),
        migrations.AddField(
            model_name="exerciseslot",
            name="tempo",
            field=models.CharField(blank=True, max_length=64, verbose_name="Tempo"),
        ),
        migrations.AddField(
            model_name="prescription",
            name="line",
            field=models.PositiveIntegerField(default=0, verbose_name="Line"),
        ),
        migrations.AddField(
            model_name="prescription",
            name="text",
            field=models.TextField(blank=True, verbose_name="Text"),
        ),
        migrations.AddConstraint(
            model_name="prescription",
            constraint=models.UniqueConstraint(
                fields=("exercise_slot", "week", "line"),
                name="unique_cell_slot_week_line",
            ),
        ),
        # Compose text / hoist rest / sub-lines / wipe undo stacks / convert
        # delivery payloads — runs while BOTH the old and new columns exist
        # (adds above, removes below). Irreversible in substance; the reverse
        # direction just restores empty old columns via the RemoveField
        # reverses, so noop here.
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
