# Generated by Django 6.0.6 on 2026-07-17 01:20
#
# 2c (spreadsheet-parity plan §3.1, D1): remove the MesoGroup subsystem.
# Before the schema drop, a data step deletes the group-rooted *shared* plans
# (``relationship`` NULL — orphans once ``Plan.group`` is gone; demo-only data
# in practice). A member's *materialized* group-delivery plan keeps its
# ``relationship`` root and simply survives as an ordinary individual plan —
# exactly the new model, so no data step touches it. Historical
# ``AgentProposalBatch.trigger="group"`` / ``ProposedChange.kind="adjust"``
# rows are left in place: choices aren't DB-enforced and rewriting them would
# falsify the usage ledger.

from django.db import migrations
from django.db import models


def delete_shared_group_plans(apps, schema_editor):
    Plan = apps.get_model("meso", "Plan")
    # ORM delete so the cascade walks the whole tree (mesocycles → weeks →
    # cells → deliveries → plan actions → agent batches) in Python, matching
    # the FKs as of this migration state.
    Plan.objects.filter(relationship__isnull=True).delete()


def flush_deferred_constraints(apps, schema_editor):
    """Force Postgres to check + clear the deferred RI triggers queued above.

    HAZARD (do not remove): on PostgreSQL, the ORM cascade delete in
    ``delete_shared_group_plans`` queues deferred RI trigger events on every
    table FK'd off ``Plan`` (and its children — mesocycles, weeks, slots,
    cells, ...), because this app's FK constraints are
    ``DEFERRABLE INITIALLY DEFERRED``. Postgres refuses to ``ALTER TABLE`` a
    table with pending trigger events *in the same transaction*, and the very
    next operations below do exactly that to ``meso_plan``. On an empty
    database the delete matches zero rows and queues nothing, so this only
    bites a database that actually has group-rooted plans (a restore, or a
    local/staging DB with real data) — which is why it can pass CI/prod and
    still fail elsewhere. ``SET CONSTRAINTS ALL IMMEDIATE`` forces Postgres to
    check and clear those queued events right here, before the ALTERs, while
    keeping the whole migration in one atomic transaction. See 0036/0037 for
    the earlier occurrence of this same hazard (there, split across two
    migrations instead — not an option here since prod already has this
    migration recorded as applied).

    Guarded to Postgres only: ``SET CONSTRAINTS`` is invalid syntax on
    SQLite, which is what this suite's default test settings
    (``config.settings.test``) run on — an unconditional ``RunSQL`` here
    breaks every migration-touching test.
    """
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("SET CONSTRAINTS ALL IMMEDIATE")


class Migration(migrations.Migration):

    dependencies = [
        ("meso", "0039_drop_structured_cell_columns"),
    ]

    operations = [
        migrations.RunPython(
            delete_shared_group_plans, migrations.RunPython.noop, elidable=True
        ),
        migrations.RunPython(
            flush_deferred_constraints, migrations.RunPython.noop, elidable=True
        ),
        migrations.RemoveConstraint(
            model_name="groupmembership",
            name="unique_group_membership",
        ),
        migrations.RemoveField(
            model_name="proposedchange",
            name="membership",
        ),
        migrations.RemoveField(
            model_name="mesogroup",
            name="coach",
        ),
        migrations.RemoveConstraint(
            model_name="prescriptionoverride",
            name="unique_prescription_override",
        ),
        migrations.RemoveConstraint(
            model_name="plan",
            name="plan_relationship_xor_group",
        ),
        migrations.RemoveConstraint(
            model_name="plan",
            name="unique_materialized_group_plan",
        ),
        migrations.AlterField(
            model_name="agentproposalbatch",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("draft", "Draft with AI"),
                    ("eval", "Eval"),
                ],
                default="manual",
                max_length=16,
                verbose_name="Trigger",
            ),
        ),
        migrations.AlterField(
            model_name="proposedchange",
            name="kind",
            field=models.CharField(
                choices=[
                    ("swap", "Swap"),
                    ("progress", "Progress"),
                    ("volume", "Volume"),
                    ("deload", "Deload"),
                    ("add", "Add"),
                ],
                max_length=16,
                verbose_name="Kind",
            ),
        ),
        migrations.AlterField(
            model_name="tourevent",
            name="segment",
            field=models.CharField(
                blank=True,
                help_text="For opt_in events only: the demo segment (athletes/program/delivery/log) or self-variant action (roster_add_self/plan_create) that was opted into.",
                max_length=32,
                verbose_name="Segment / action",
            ),
        ),
        migrations.RemoveField(
            model_name="prescriptionoverride",
            name="membership",
        ),
        migrations.RemoveField(
            model_name="prescriptionoverride",
            name="prescription",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="group",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="source_group",
        ),
        migrations.DeleteModel(
            name="GroupMembership",
        ),
        migrations.DeleteModel(
            name="PrescriptionOverride",
        ),
        migrations.DeleteModel(
            name="MesoGroup",
        ),
    ]
