# Generated by Django 6.0.6 on 2026-07-17 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meso", "0040_remove_group_subsystem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="is_template",
            field=models.BooleanField(default=False, verbose_name="Template"),
        ),
        migrations.AddField(
            model_name="plan",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template_plans",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="plan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_template", False),
                    ("relationship__isnull", True),
                    _connector="OR",
                ),
                name="template_plan_has_no_relationship",
            ),
        ),
    ]
