# Generated by Django 6.0.6 on 2026-07-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meso", "0041_template_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="athlete_authored",
            field=models.BooleanField(default=False, verbose_name="Athlete authored"),
        ),
    ]
