# Generated by Django 6.0.6 on 2026-07-18 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meso", "0042_prescription_athlete_authored"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="week",
            name="is_current",
        ),
    ]
