# Generated by Django 6.0.6 on 2026-07-18 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meso", "0043_remove_week_is_current"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentproposalbatch",
            name="mesocycle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proposal_batches",
                to="meso.mesocycle",
                verbose_name="Block",
            ),
        ),
    ]
