# Generated by Django 6.0.6 on 2026-07-20 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meso", "0044_agent_proposal_batch_mesocycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="loggedset",
            name="source_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parsed_sets",
                to="meso.prescription",
                verbose_name="Source line",
            ),
        ),
    ]
