# Generated by Django 6.0.6 on 2026-09-19 01:12

import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meso", "0045_loggedset_source_line"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionlog",
            name="last_activity_at",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now(),
                default=django.utils.timezone.now,
                verbose_name="Last activity",
            ),
        ),
    ]
