# Generated by Django 6.0.6 on 2026-09-19 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meso", "0047_register_settle_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="loggedset",
            name="reclaimed_line",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reclaimed_sets",
                to="meso.prescription",
                verbose_name="Reclaimed line",
            ),
        ),
    ]
