# Generated by Django 6.0.6 on 2026-09-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meso", "0048_loggedset_reclaimed_line"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachsubscription",
            name="cancel_at",
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    "Mirrored from Stripe: when a cancelled subscription ends "
                    "(Stripe's cancel_at, or the period end when "
                    "cancel_at_period_end is set). Null = not scheduled to end."
                ),
                null=True,
                verbose_name="Scheduled to end at",
            ),
        ),
    ]
