# Generated by Django 6.0.6 on 2026-09-20 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meso", "0049_coachsubscription_cancel_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="loggedset",
            name="exercise_slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logged_sets",
                to="meso.exerciseslot",
                verbose_name="Exercise slot",
            ),
        ),
    ]
