# Generated by Django 6.0.6 on 2026-09-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meso', '0051_backfill_loggedset_exercise_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachathlete',
            name='label',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name="Coach's label for the athlete"),
        ),
        migrations.AddField(
            model_name='coachinvite',
            name='label',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name="Coach's label for the athlete"),
        ),
    ]
