# Generated by Django 6.0.6 on 2026-09-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meso', '0052_coachathlete_label_coachinvite_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteprofile',
            name='goals',
            field=models.TextField(blank=True, verbose_name='Goals'),
        ),
    ]
