# Generated by Django 6.0.6 on 2026-09-27

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("meso", "0053_athleteprofile_goals"),
    ]

    operations = [
        migrations.AddField(
            model_name="athleteprofile",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[("kg", "Kilograms"), ("lb", "Pounds")],
                max_length=2,
                verbose_name="Unit",
            ),
        ),
    ]
