# Generated by Django 6.0.6 on 2026-09-27

from django.db import migrations
from django.db import models


class Unit(models.TextChoices):
    KILOGRAMS = "kg", "Kilograms"
    POUNDS = "lb", "Pounds"


def backfill_logged_set_units(apps, schema_editor):
    LoggedSet = apps.get_model("meso", "LoggedSet")
    db_alias = schema_editor.connection.alias
    plan_unit_lookup = "session_log__session__week__mesocycle__plan__unit"

    for unit in (Unit.KILOGRAMS, Unit.POUNDS):
        LoggedSet.objects.using(db_alias).filter(**{plan_unit_lookup: unit}).update(
            unit=unit
        )


class Migration(migrations.Migration):
    dependencies = [
        ("meso", "0054_athleteprofile_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="loggedset",
            name="unit",
            field=models.CharField(
                choices=[("kg", "Kilograms"), ("lb", "Pounds")],
                default="kg",
                max_length=2,
                verbose_name="Unit",
            ),
        ),
        migrations.RunPython(
            backfill_logged_set_units,
            migrations.RunPython.noop,
        ),
    ]
