# Generated by Django 6.0.6 on 2026-10-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meso', '0056_alter_coachprofile_default_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachathlete',
            name='ended_archived_plans',
            field=models.JSONField(blank=True, default=dict, verbose_name='Plans archived by ending'),
        ),
        migrations.AddField(
            model_name='coachathlete',
            name='ended_by',
            field=models.CharField(blank=True, choices=[('coach', 'Coach'), ('athlete', 'Athlete')], default='', max_length=8, verbose_name='Ended by'),
        ),
        migrations.AlterField(
            model_name='coachathlete',
            name='status',
            field=models.CharField(choices=[('pending_coach_invite', 'Pending athlete acceptance'), ('pending_athlete_request', 'Pending coach acceptance'), ('active', 'Active'), ('accepted_waiting', "Accepted, waiting on coach's plan"), ('declined', 'Declined'), ('ended', 'Ended')], max_length=32, verbose_name='Status'),
        ),
    ]
