# Generated by Django 6.0.6 on 2026-10-01 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meso', '0057_trust_649_651'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='for_invite',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_templates', to='meso.coachinvite', verbose_name='Written for invite'),
        ),
    ]
