# Generated by Django 6.0.6 on 2026-10-02 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meso', '0060_drop_loggedset_reclaimed_line_column'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sessionlog',
            constraint=models.UniqueConstraint(fields=('session', 'athlete'), name='meso_sessionlog_one_per_athlete_session'),
        ),
    ]
