# Generated by Django 6.0.6 on 2026-10-02 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20201204_2000'),
        ('meso', '0061_sessionlog_one_per_athlete_session_699'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedset',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meso_logged_sets', to='exercises.exercise', verbose_name='Catalog exercise (as logged)'),
        ),
        migrations.AddField(
            model_name='loggedset',
            name='exercise_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Exercise name (as logged)'),
        ),
    ]
