# Generated by Django 6.0.6 on 2026-10-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meso', '0063_backfill_loggedset_lift_stamp_708'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='client_token',
            field=models.CharField(blank=True, db_default='', default='', max_length=64, verbose_name='Client token'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='entered_by_coach',
            field=models.BooleanField(db_default=False, default=False, verbose_name='Entered by coach'),
        ),
    ]
