# Generated by Django 6.0.6 on 2026-10-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meso', '0065_coach_set_attribution_719'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='sync_version',
            field=models.PositiveBigIntegerField(db_default=0, default=0, verbose_name='Sync version'),
        ),
    ]
