# Generated by Django 6.0.6 on 2026-10-03 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meso", "0066_plan_sync_version_709"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loggedset",
            name="exercise_slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="logged_sets",
                to="meso.exerciseslot",
                verbose_name="Exercise slot",
            ),
        ),
        migrations.AlterField(
            model_name="sessionlog",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="logs",
                to="meso.session",
                verbose_name="Session",
            ),
        ),
    ]
