# Generated by Django 3.2.11 on 2022-08-19 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_coach'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='coach',
            new_name='is_coach',
        ),
    ]
