# Generated by Django 5.2.4 on 2025-07-19 14:09

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_squashed_0002_auto_20201121_1727"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateField(
                blank=True,
                help_text="Please use the following format: YYYY-MM-DD",
                null=True,
                verbose_name="Birthday",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="points",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Points",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="sex",
            field=models.CharField(
                choices=[("U", "Prefer not to say"), ("M", "Male"), ("F", "Female")],
                default="U",
                max_length=1,
                verbose_name="Sex",
            ),
        ),
    ]
