# Generated by Django 3.1.6 on 2021-02-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Short description of product'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Short description of product'),
        ),
    ]
