# Generated by Django 3.1 on 2020-08-31 01:54

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_program_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                upload_to="products/images/",
                verbose_name="Featured product image",
            ),
        ),
    ]
