# Generated by Django 3.2.11 on 2022-08-20 04:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_auto_20220820_0447'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accountability',
            new_name='Subscription',
        ),
    ]
