# Generated by Django 3.2.11 on 2022-08-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_accountability_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billing_interval',
            field=models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], default='month', max_length=5),
        ),
    ]
