# Generated by Django 3.2.11 on 2022-08-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20220826_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='aggregate_usage',
            field=models.CharField(blank=True, choices=[('sum', 'All usage during period'), ('last_during_period', 'Last usage record reported within a period'), ('last_ever', 'Last usage record ever (across period bounds)'), ('max', 'Maximum reported usage during a period')], default=None, help_text='Specifices a usage aggregation strategy for prices of `usage_type=metered`', max_length=18),
        ),
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD')], default='USD', max_length=3),
        ),
    ]
