# Generated by Django 3.2.11 on 2022-08-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20220826_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='aggregate_usage',
            field=models.CharField(choices=[('sum', 'All usage during period'), ('last_during_period', 'Last usage record reported within a period'), ('last_ever', 'Last usage record ever (across period bounds)'), ('max', 'Maximum reported usage during a period')], default=None, help_text='Specifices a usage aggregation strategy for prices of `usage_type=metered`', max_length=18, null=True),
        ),
    ]
