# Generated by Django 3.2.11 on 2022-08-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20220826_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='aggregate_usage',
            field=models.CharField(choices=[('None', '---------'), ('sum', 'All usage during period'), ('last_during_period', 'Last usage record reported within a period'), ('last_ever', 'Last usage record ever (across period bounds)'), ('max', 'Maximum reported usage during a period')], default=None, help_text='Specifices a usage aggregation strategy for prices of `usage_type=metered`', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='billing_scheme',
            field=models.CharField(choices=[('None', '---------'), ('tiered', '`tiered`: unit pricing will be computed using a tiered strategy defined with `tiers` and `tiers_mode`'), ('per_unit', '`per_unit`: the fixed amount will be charged per unit in `quantity` (for prices with `usage_type=licensed`) or per unit of total usage (for prices with `usage_type=metered`)')], default='per_unit', help_text='How to compute the price per period', max_length=8),
        ),
        migrations.AlterField(
            model_name='price',
            name='interval',
            field=models.CharField(choices=[('None', '---------'), ('once', 'Once'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_type',
            field=models.CharField(choices=[('None', '---------'), ('one_time', 'One Time'), ('recurring', 'Recurring')], default='one_time', max_length=9),
        ),
        migrations.AlterField(
            model_name='price',
            name='tax_behavior',
            field=models.CharField(choices=[('None', '---------'), ('inclusive', 'The price includes tax payment'), ('exclusive', 'The price does not include tax payment'), ('unspecified', 'Tax behavior not specified')], default='unspecified', max_length=11),
        ),
        migrations.AlterField(
            model_name='price',
            name='tiers_mode',
            field=models.CharField(choices=[('None', '---------'), ('graduated', '`graduated`: pricing changes as the quantity grows'), ('volume', '`volume`: the maximum quantity within a period determines the per unit price')], default=None, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='usage_type',
            field=models.CharField(choices=[('None', '---------'), ('metered', '`metered`: aggregates the total usage based on usage records'), ('licensed', '`licensed`: automatically bills the `quantity` set when adding it to a subscription (default)')], default=None, max_length=8, null=True),
        ),
    ]
