# Generated by Django 3.2.11 on 2022-08-27 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20220826_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tier',
            name='price_obj',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='Tier',
        ),
    ]
