# Generated by Django 3.2.11 on 2022-08-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20220827_1508'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='price',
            name='products_price_aggregate_usage_is_metered',
        ),
        migrations.RemoveConstraint(
            model_name='price',
            name='products_price_tiered_billing_without_unit_amount',
        ),
        migrations.RemoveConstraint(
            model_name='price',
            name='products_price_unit_billing_has_unit_amount',
        ),
        migrations.RemoveConstraint(
            model_name='price',
            name='products_price_unit_billing_is_not_tiered',
        ),
        migrations.RemoveConstraint(
            model_name='price',
            name='products_price_recurring_interval_one_year_or_less',
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('price_type', 'one_time'), ('unit_amount__isnull', False)), models.Q(('price_type', 'recurring'), ('unit_amount__isnull', True)), _connector='OR'), name='products_price__price_type_with_amount'),
        ),
    ]
