# Generated by Django 3.2.11 on 2022-08-27 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20220827_1554'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='price',
            name='products_price__price_type_with_amount',
        ),
    ]
