# Generated by Django 3.1 on 2020-09-01 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80, verbose_name="Page title")),
                (
                    "content",
                    markdownx.models.MarkdownxField(
                        default="", verbose_name="Page content, in markdown"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        default="",
                        max_length=80,
                        unique=True,
                        verbose_name="Slug for page",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
