# Generated by Django 3.2 on 2022-08-30 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0002_auto_20220830_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(help_text='Whole number')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Time last modified')),
                ('unit', models.CharField(choices=[('mi', 'Miles'), ('m', 'Meters'), ('ft', 'Feet'), ('in', 'Inches'), ('yd', 'Yards')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DurationMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Time last modified')),
                ('value', models.DurationField()),
                ('unit', models.CharField(choices=[('d', 'Duration'), ('s', 'Seconds'), ('μs', 'Microseconds')], default='d', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoadMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(help_text='Whole number')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Time last modified')),
                ('unit', models.CharField(choices=[('lb', 'Pounds'), ('kg', 'Kilograms')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PowerMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(help_text='Whole number')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Time last modified')),
                ('unit', models.CharField(choices=[('W', 'Watts')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='test',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Person who added the test'),
        ),
        migrations.DeleteModel(
            name='Measure',
        ),
        migrations.AddField(
            model_name='powermeasure',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.test'),
        ),
        migrations.AddField(
            model_name='powermeasure',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loadmeasure',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.test'),
        ),
        migrations.AddField(
            model_name='loadmeasure',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='durationmeasure',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.test'),
        ),
        migrations.AddField(
            model_name='durationmeasure',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distancemeasure',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.test'),
        ),
        migrations.AddField(
            model_name='distancemeasure',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
