# Generated by Django 3.2 on 2022-08-31 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tracking', '0005_alter_test_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='content_type',
        ),
        migrations.AddField(
            model_name='test',
            name='test_content_type',
            field=models.ForeignKey(default=None, limit_choices_to=models.Q(('model', 'loadmeasure'), ('model', 'powermeasure'), ('model', 'distancemeasure'), ('model', 'durationmeasure'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Type of measurement'),
        ),
    ]
