# Generated by Django 3.2 on 2022-08-31 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_auto_20220831_0432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='test_content_type',
            new_name='measurement_content_type',
        ),
    ]
