# Generated by Django 3.2 on 2022-09-02 14:37

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_rename_measurement_content_type_test_measurement_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='video_link',
        ),
        migrations.AddField(
            model_name='test',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=None, null=True),
        ),
    ]
