# Generated by Django 3.2 on 2022-09-02 14:39

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_auto_20220902_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, default=None, null=True),
        ),
    ]
