# Generated by Django 3.2 on 2022-09-02 14:40

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_alter_test_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, default=None),
        ),
    ]
