# Generated by Django 5.2.4 on 2025-07-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0002_challenge_difficulty_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="summary",
            field=models.CharField(
                blank=True, help_text="Brief description for list view", max_length=300
            ),
        ),
    ]
