# Generated by Django 3.0.4 on 2020-03-27 18:07

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0002_challenge_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="challenge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="challenges.Challenge",
            ),
        ),
    ]
