# Generated by Django 5.2.4 on 2025-07-23 12:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_challenge_summary'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['difficulty_level'], name='challenges__difficu_d191ee_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['date_created'], name='challenges__date_cr_7a2bed_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['date_recorded'], name='challenges__date_re_893ab3_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['time_score'], name='challenges__time_sc_bd870f_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['challenge', 'date_recorded'], name='challenges__challen_234908_idx'),
        ),
    ]
