# Generated by Django 3.0.4 on 2020-03-28 14:56

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0003_auto_20200327_1807"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="time_score",
            field=models.DurationField(help_text="How long did it take you? HH:MM:SS"),
        ),
    ]
