# Generated by Django 5.2.4 on 2025-07-23 13:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0004_challenge_challenges__difficu_d191ee_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChallengeTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Challenge Tag ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Tag name")),
                (
                    "slug",
                    models.SlugField(
                        default="", unique=True, verbose_name="Slug for tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Challenge Tag",
                "verbose_name_plural": "Challenge Tags",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="challenge",
            name="challenge_tags",
            field=models.ManyToManyField(
                blank=True, to="challenges.challengetag", verbose_name="Challenge tags"
            ),
        ),
    ]
