# Generated by Django 3.0.4 on 2020-03-28 17:03

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0003_taggeditem_add_unique_index"),
        ("challenges", "0004_auto_20200328_1456"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
