# Generated by Django 3.0.4 on 2020-03-31 19:02

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0005_challenge_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="notes",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
