# Generated by Django 5.2.4 on 2025-07-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0006_auto_20250723_1310"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="tags",
        ),
    ]
