# Generated by Django 5.2.4 on 2025-08-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_remove_tags_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
