# pull official base image
FROM python:3.11.2

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements/base.txt .
COPY ./requirements/production.txt .
RUN pip install -r production.txt

# copy project
COPY . .

# collect static files
RUN python3 manage.py collectstatic --noinput

# migrate database
RUN python3 manage.py migrate --noinput
