# Generated by Django 3.1 on 2020-10-22 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent', models.BooleanField(default=False)),
                ('sender', models.EmailField(default='Lance Goyke <lance@lancegoyke.com>', max_length=254)),
                ('subject', models.CharField(max_length=78, verbose_name='Subject')),
                ('html_body', markdownx.models.MarkdownxField(default='', verbose_name='HTML content, in markdown')),
                ('text_body', models.TextField(default='', verbose_name='Text content')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
