# Generated by Django 3.1 on 2020-10-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='sender',
            field=models.CharField(default='Lance Goyke <lance@lancegoyke.com>', max_length=150, verbose_name='Address sending the email'),
        ),
    ]
