# Generated by Django 6.0.6 on 2026-09-18 22:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SentEmail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ses_message_id", models.CharField(max_length=255, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("block_delivered", "Block delivered"),
                            ("coach_invite", "Coach invite"),
                            ("invite_reminder", "Invite reminder"),
                            ("coach_request", "Coach request"),
                            ("contact_owner", "Contact form (owner copy)"),
                            ("contact_ack", "Contact form (sender ack)"),
                            ("margin_alert", "Margin alert"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=32,
                    ),
                ),
                ("recipient", models.EmailField(db_index=True, max_length=254)),
                ("subject", models.CharField(blank=True, max_length=998)),
                (
                    "sent_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sent email",
                "verbose_name_plural": "Sent emails",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("send", "Send"),
                            ("delivery", "Delivery"),
                            ("open", "Open"),
                            ("click", "Click"),
                            ("bounce", "Bounce"),
                            ("complaint", "Complaint"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("ses_message_id", models.CharField(db_index=True, max_length=255)),
                ("sns_message_id", models.CharField(max_length=255)),
                ("recipient", models.EmailField(blank=True, max_length=254)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("block_delivered", "Block delivered"),
                            ("coach_invite", "Coach invite"),
                            ("invite_reminder", "Invite reminder"),
                            ("coach_request", "Coach request"),
                            ("contact_owner", "Contact form (owner copy)"),
                            ("contact_ack", "Contact form (sender ack)"),
                            ("margin_alert", "Margin alert"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=32,
                    ),
                ),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("is_bot", models.CharField(blank=True, max_length=16)),
                ("link", models.URLField(blank=True, max_length=2048)),
                ("bounce_type", models.CharField(blank=True, max_length=32)),
                ("bounce_subtype", models.CharField(blank=True, max_length=32)),
                ("raw", models.JSONField(default=dict)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "sent_email",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="notifications.sentemail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email event",
                "verbose_name_plural": "Email events",
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "occurred_at"],
                        name="notificatio_event_t_7c445b_idx",
                    ),
                    models.Index(
                        fields=["kind", "occurred_at"],
                        name="notificatio_kind_98463f_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sns_message_id", "recipient"),
                        name="uniq_email_event_per_sns_message_recipient",
                    )
                ],
            },
        ),
    ]
