# Generated by Django 6.0.6 on 2026-09-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailevent',
            name='kind',
            field=models.CharField(choices=[('block_delivered', 'Block delivered'), ('coach_invite', 'Coach invite'), ('invite_reminder', 'Invite reminder'), ('coach_request', 'Coach request'), ('contact_owner', 'Contact form (owner copy)'), ('contact_ack', 'Contact form (sender ack)'), ('margin_alert', 'Margin alert'), ('order_confirmation', 'Order confirmation'), ('account_confirmation', 'Account confirmation'), ('password_reset', 'Password reset'), ('account_notice', 'Account notice'), ('other', 'Other')], db_index=True, default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='kind',
            field=models.CharField(choices=[('block_delivered', 'Block delivered'), ('coach_invite', 'Coach invite'), ('invite_reminder', 'Invite reminder'), ('coach_request', 'Coach request'), ('contact_owner', 'Contact form (owner copy)'), ('contact_ack', 'Contact form (sender ack)'), ('margin_alert', 'Margin alert'), ('order_confirmation', 'Order confirmation'), ('account_confirmation', 'Account confirmation'), ('password_reset', 'Password reset'), ('account_notice', 'Account notice'), ('other', 'Other')], db_index=True, default='other', max_length=32),
        ),
    ]
