# Generated by Django 4.1.7 on 2023-05-04 23:55

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_honeypot", "0002_auto_20160208_0854"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginattempt",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
