# Generated by Django 3.1.2 on 2020-12-04 17:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0002_auto_20201204_1648"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Category ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Category name")),
                (
                    "slug",
                    models.SlugField(
                        default="", unique=True, verbose_name="Slug for category"
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="exercise",
            name="category",
            field=models.ManyToManyField(
                blank=True, to="exercises.Category", verbose_name="Exercise category"
            ),
        ),
    ]
