# Generated by Django 3.2 on 2022-11-11 02:11

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('unit', models.CharField(max_length=30)),
                ('fiber', models.PositiveSmallIntegerField()),
                ('cals', models.PositiveSmallIntegerField()),
                ('fat', models.PositiveSmallIntegerField()),
                ('carbs', models.PositiveSmallIntegerField()),
                ('net_carbs', models.PositiveSmallIntegerField()),
                ('net_cals', models.PositiveSmallIntegerField()),
                ('protein', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fat', models.PositiveSmallIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ingredients', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('cals', models.PositiveSmallIntegerField()),
                ('fiber', models.PositiveSmallIntegerField()),
                ('protein', models.PositiveSmallIntegerField()),
                ('net_carbs', models.PositiveSmallIntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=2000)),
                ('net_cals', models.PositiveSmallIntegerField()),
                ('carbs', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
