# Generated by Django 3.2 on 2022-11-12 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
