# Generated by Django 3.2 on 2022-11-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_auto_20221112_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=10)),
                ('unit_id', models.UUIDField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
