# Generated by Django 3.2 on 2022-11-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_nutrient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrient',
            name='unit',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='unit_id',
            field=models.UUIDField(null=True),
        ),
    ]
