# Generated by Django 3.2 on 2022-11-12 16:22
import requests
import sys
from typing import Dict, List

from django.conf import settings
from django.db import migrations

from store_project.meals import models


def forwards_func(apps, schema_editor):
    models.Unit.objects.all().delete()
    models.Nutrient.objects.all().delete()

    units_endpoint = "https://nutrition-api.esha.com/units"
    nutrients_endpoint = "https://nutrition-api.esha.com/nutrients"

    headers = {
        "Accept": "application/json",
        "Ocp-Apim-Subscription-Key": settings.ESHA_SUB_KEY,
    }

    # UNITS OF MEASUREMENT
    r = requests.get(units_endpoint, headers=headers)
    units: List[Dict] = r.json()
    count = 0
    for u in units:
        models.Unit.objects.create(
            id=u["id"],
            description=u["description"],
            abbr=u["abbr"],
        )
        count = count + 1
    sys.stdout.write(f"\nAdded {count} units of measurement...")

    # NUTRIENTS
    r = requests.get(nutrients_endpoint, headers=headers)
    nutrients: List[Dict] = r.json()
    count = 0
    for n in nutrients:
        models.Nutrient.objects.create(
            id=n["id"],
            description=n["description"],
            unit=n.get("unit", None),
            unit_id=n.get("unitId", None),
        )
        count = count + 1
    sys.stdout.write(f"\nAdded {count} nutrients...")


def reverse_func(apps, schema_editor):
    # delete the data
    models.Unit.objects.all().delete()
    models.Nutrient.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_auto_20221112_1615'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
