# Generated by Django 3.2 on 2022-11-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_alter_ingredient_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='spoon_id',
            field=models.CharField(default='1', max_length=25),
            preserve_default=False,
        ),
    ]
