name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      SECRET_KEY: NotSecureForTesting
      PYTHONUNBUFFERED: 1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      FB_APP_ID: ${{ secrets.FB_APP_ID }}
      FB_SECRET_KEY: ${{ secrets.FB_SECRET_KEY }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      STRIPE_ENDPOINT_SECRET: ${{ secrets.STRIPE_ENDPOINT_SECRET }}
      STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      G_RECAPTCHA_SITE_KEY: test-recaptcha-site-key
      G_RECAPTCHA_SECRET_KEY: test-recaptcha-secret-key
      G_RECAPTCHA_ENDPOINT: https://test-recaptcha-endpoint.com

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        id: setup_python
        with:
          python-version-file: "pyproject.toml"

      - name: Install apt dependencies
        run: sudo apt-get update && sudo apt-get install swig

      - name: Install UV
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.20"

      - name: Cache UV dependencies
        uses: actions/cache@v4
        with:
          key: venv-${{ runner.os }}-${{ steps.setup_python.outputs.python-version}}-${{ hashFiles('uv.lock') }}
          path: .venv

      - name: Install Python dependencies
        run: uv sync --all-extras

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files --color=always

      - name: run system checks
        run: cd app && uv run python manage.py check --deploy

      - name: check for migrations
        run: cd app && uv run python manage.py makemigrations --check

      - name: Run Tests
        run: |
          cd app && uv run pytest
